### ISSUE TITLE
Autoplank causes desktop to lag

### ISSUE THREAD

**Issue by logix2** [abiosoft/autoplank#1]
This is the issue we were talking about on Reddit: [https://www.reddit.com/r/elementaryos/comments/95a879/autoplank_use_plank_on_multimonitor_setup/e3tmfas/](https://www.reddit.com/r/elementaryos/comments/95a879/autoplank_use_plank_on_multimonitor_setup/e3tmfas/).

My Gnome desktop lags like crazy and I get increased CPU usage for some Xorg process that's usually near 0%.

Here's a htop screenshot: https://i.imgur.com/Jj1bLHs.png While the CPU usage is not very high for that process, it's usually around 0 CPU usage until I run autoplank, and the desktop gets very choppy (mouse movement and dragging windows) and laggy while autoplank runs.

I'm using Ubuntu 18.04 with Gnome desktop, Nvidia 980 gtx graphics with proprietary nvidia drivers in case that matters. Also in case it matters: I'm using 2 monitors with different resolutions and aspect ratios: 2560x1080 (21:9) and 1920x1080 (16:9).

Plank version:
```
$ apt-cache policy plank
plank:
  Installed: 0.11.4-2
  Candidate: 0.11.4-2
  Version table:
 *** 0.11.4-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Let me know what I can do to debug this.

**Comment by logix2** [comment]
By the way, if I change

```
		for range time.Tick(time.Millisecond * 500) {
```
to:
```
		for range time.Tick(time.Millisecond * 1500) {
```
In autoplank, the desktop feels less choppy (although a bit of lag can still be observed). The Xorg process I was mentioning still has some pretty high CPU usage with this new millisecond value though, somewhere between 10-30%.

**Comment by abiosoft** [comment]
I initially set the value to `2000` which should be fine for most people. I assume it has something to do with the graphics card.

I'll update this issue when I make changes so you can help verify.

**Comment by abiosoft** [comment]
@logix2 do you mind updating now and see if there is any difference?

**Comment by logix2** [comment]
I'm no longer noticing any desktop lag with the latest Git. I guess this can be considered fixed. I'll leave autoplank running and let you know if I notice anything.
