### ISSUE TITLE
External monitors only display plank after displaying plank on built-in monitor

### ISSUE THREAD

**Issue by ezrafree** [abiosoft/autoplank#8]
I have a laptop with two external monitors connected to it. I keep the laptop lid opened and use its built-in monitor as a third monitor.

I have plank set in autohide mode.

If I raise plank on the built-in monitor, it will then only display on whichever of the two external monitors I display it on next, but not the other.

Please let me know if there's any other info I can provide that would be useful.

**Comment by tv78-coder** [comment]
Maybe you can try Elementary OS 5.1 Hera, currently i have no issue with that.
